tenderloin_android_defconfig: Do not set CONFIG_FIB_RULES
Since compilation will fail with:

arm-webos-linux-gnueabi-ld.bfd: net/built-in.o: in function `fib_nl_fill_rule':
| fib_rules.c:(.text+0x25afc): undefined reference to `from_kuid_munged'
| arm-webos-linux-gnueabi-ld.bfd: fib_rules.c:(.text+0x25b14): undefined reference to `from_kuid_munged'
| arm-webos-linux-gnueabi-ld.bfd: net/built-in.o: in function `nla_get_kuid_range':
| fib_rules.c:(.text+0x25d2c): undefined reference to `make_kuid'
| arm-webos-linux-gnueabi-ld.bfd: fib_rules.c:(.text+0x25d44): undefined reference to `make_kuid'
| arm-webos-linux-gnueabi-ld.bfd: net/built-in.o: in function `rt_fill_info.constprop.0':
| route.c:(.text+0x6a0b0): undefined reference to `from_kuid_munged'
| arm-webos-linux-gnueabi-ld.bfd: net/built-in.o: in function `inet_rtm_getroute':
| route.c:(.text+0x6c1a4): undefined reference to `make_kuid'
| arm-webos-linux-gnueabi-ld.bfd: net/built-in.o: in function `inet6_rtm_getroute':
| route.c:(.text+0xdadc4): undefined reference to `make_kuid'
| make[2]: *** [/home/herrie/LuneOS/gatesgarth/webos-ports/tmp-glibc/work-shared/tenderloin/kernel-source/Makefile:885: .tmp_vmlinux1] Error 1

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>