compiler-gcc: integrate the various compiler-gcc[345].h files
As gcc major version numbers are going to advance rather rapidly in the
future, there's no real value in separate files for each compiler
version.

Deduplicate some of the macros #defined in each file too.

Neaten comments using normal kernel commenting style.

Backport note (not part of the original commit message), for this tree:
include/linux/compiler-gcc.h pastes __GNUC__ into the name of the header it
includes, and this tree only has compiler-gcc3.h, -gcc4.h and -gcc5.h. With a
current compiler (GCC 15 here) the first translation unit fails:

  include/linux/compiler-gcc.h:106:1: fatal error: linux/compiler-gcc15.h:
  No such file or directory

Use the hammerhead Halium tree's merged compiler-gcc.h, which keys everything
on GCC_VERSION and works for any GCC, and drop the three per-version headers
it replaces. This is Joe Perches' "compiler-gcc: integrate the various
compiler-gcc[345].h files" (shr-distribution/linux 5f1f9f682283), which is the
last commit to touch that file in the hammerhead tree.

Signed-off-by: Joe Perches <joe@perches.com>
Cc: Andi Kleen <andi@firstfloor.org>
Cc: Michal Marek <mmarek@suse.cz>
Cc: Segher Boessenkool <segher@kernel.crashing.org>
Cc: Sasha Levin <levinsasha928@gmail.com>
Cc: Anton Blanchard <anton@samba.org>
Cc: Alan Modra <amodra@gmail.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
Upstream-Status: Backport [shr-distribution/linux hammerhead/3.4/halium-9.0 5f1f9f682283]