watchdog: s3c2410_wdt: fix printk format compilation errors
Without that fix we have:
  drivers/watchdog/s3c2410_wdt.c: In function ‘watchdog_init’:
  drivers/watchdog/s3c2410_wdt.c:542:0: error: unterminated argument list invoking macro "pr_info"
  [...]

This problem has been introduced by the commit 1ab73c46629484053953e678328b0a115a39ed3b
  "watchdog: Use pr_<fmt> and pr_<level>".

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@no-log.org>