fix build errors using gcc-4.7
error: DIV usage mismatch between arch/arm/boot/compressed/misc.o and output
error: DIV usage mismatch between arch/arm/boot/compressed/lib1funcs.o and output

Change-Id: I1251b843bb9b4c74ba8039fd194e3aed2183cf5b

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

Conflicts:

	arch/arm/boot/compressed/Makefile